use_frameworks!

target 'HMHClassKitHelper_Example' do
  pod 'HMHClassKitHelper', :path => '../'

  target 'HMHClassKitHelper_Tests' do
    inherit! :search_paths
  end
  
  target 'HMHClassKitHelper_ExtensionExample' do
    pod 'HMHClassKitHelper', :path => '../'
  end
end
